### ISSUE TITLE
PostgreSQL?

### ISSUE THREAD

**Issue by R-N** [nguyenanhung/codeigniter3-vercel-skeleton#2]
Thank you for the project. My CodeIgniter projects run well with some adjustments. But I'm having a problem for the database. 

I want to use Vercel's PostgreSQL but I can't. 

- If I use 'pdo' dbdriver, the error is  "could not find driver" or "Invalid or non-existent PDO subdriver". 
- If I use 'postgre' dbdriver, the error is "Call to undefined function pg_connect()". 

I think it's because postgre driver (php_pgsql.dll) or its pdo subdriver (php_pdo_pgsql.dll) aren't enabled by default in PHP. How do I enable them? Idk if the names are the same in linux though.

I can connect to the database just fine with DBeaver so I think I'm configurating it right. Though I'm not sure if I'm putting the "sslmode=require" correctly. 

```
$db['default'] = array(
    'dsn'   => 'pgsql:host=x.y.aws.neon.tech;port=5432;dbname=verceldb;sslmode=require',
    'hostname' => 'x.y.aws.neon.tech',
    'port'     => 5432,
    'username' => 'username',
    'password' => 'password',
    'database' => 'verceldb',
    'dbdriver' => 'pdo', //or postgre
    'dbprefix' => '',
     ...
)
```

pdo dbdriver error:

```
A Database Error Occurred
could not find driver

Filename: /var/task/user/vendor/nguyenanhung/codeigniter-framework/hungng/HungNG_CI_Base_Controllers.php

Line Number: 74
```

postgre dbdriver error:
```
An uncaught Exception was encountered
Type: Error

Message: Call to undefined function pg_connect()

Filename: /var/task/user/vendor/nguyenanhung/codeigniter-framework/system/database/drivers/postgre/postgre_driver.php

Line Number: 146

Backtrace:

File: /var/task/user/vendor/nguyenanhung/codeigniter-framework/thirdParty/MX/Loader.php
Line: 146
Function: DB

File: /var/task/user/vendor/nguyenanhung/codeigniter-framework/thirdParty/MX/Loader.php
Line: 74
Function: initialize

File: /var/task/user/vendor/nguyenanhung/codeigniter-framework/hungng/HungNG_CI_Base_Controllers.php
Line: 74
Function: __construct

File: /var/task/user/application/controllers/Main.php
Line: 7
Function: __construct

File: /var/task/user/index.php
Line: 284
Function: require_once

File: /var/task/user/api/index.php
Line: 3
Function: require
```

**Comment by R-N** [comment]
I think adding these packages works.
- ext-pgsql
- ext-pdo_pgsql
- lib-pgsql-libpq

Well it's on internal error now but it's a progress. I think it's just my project's issue now because it was developed for MySQL.

**Comment by nguyenanhung** [comment]
hi, i think Vercel environment it not supported Ps-SQL driver? 

this package limited by Vercel server

**Comment by nguyenanhung** [comment]
Thank @R-N , I will test and add soon

**Comment by nguyenanhung** [comment]
@R-N You can try again with config

```php
'dsn'   => 'pgsql:host=ep-shrill-disk-******.eu-central-1.aws.neon.tech;port=5432;dbname=php-neon;sslmode=require',
'hostname' => 'ep-shrill-disk-******.eu-central-1.aws.neon.tech',
'username' => 'daniil.bazhenov',
'password' => '************',
'database' => 'php-neon',
'dbdriver' => 'pdo',
'dbprefix' => '',
'pconnect' => TRUE, // Use persistent connection if necessary
'db_debug' => (ENVIRONMENT !== 'production'),
'cache_on' => FALSE,
'cachedir' => '',
'char_set' => 'utf8',
'dbcollat' => 'utf8_general_ci',
'sslmode' => 'require',
```

or 

```php
'hostname' => 'ep-shrill-disk-******.eu-central-1.aws.neon.tech',
'username' => 'daniil.bazhenov',
'password' => '************',
'database' => 'php-neon',
'dbdriver' => 'postgresql', // Use PostgreSQL driver directly
'dbprefix' => '',
'pconnect' => TRUE, // Use persistent connection if necessary
'db_debug' => (ENVIRONMENT !== 'production'),
'cache_on' => FALSE,
'cachedir' => '',
'char_set' => 'utf8',
'dbcollat' => 'utf8_general_ci',
'sslmode' => 'require',
```

**Comment by R-N** [comment]
I think it should be "postgre" not "postgresql" as mentioned in database.php comments. "postgresql" gives `Invalid DB driver`.

```
   ['dbdriver'] The database driver. e.g.: mysqli.
           Currently supported:
                cubrid, ibase, mssql, mysql, mysqli, oci8,
                odbc, pdo, postgre, sqlite, sqlite3, sqlsrv
```

Setting pconnect to TRUE doesn't help. Probably because the current problem is on my end, with my project. 

I've properly migrated the database but still getting internal error. No, actually, it's not "internal error". I say internal error because the response code is 500 but it actually shows nothing. An empty web page. 

It just dies on a database query, no errors. And the Vercel logs are just the 500 codes. They aren't helpful at all. I wonder why there's no error or anything? Any ideas on how to start debugging?

**Comment by nguyenanhung** [comment]
Hi @R-N , the comment above is my quick research, this weekend I will try to launch a posgresql database to debug.

**Comment by nguyenanhung** [comment]
@R-N I have set up an endpoint to check the function, the result is that the functions are still enabled: https://codeigniter3-vercel-skeleton.vercel.app/welcome/pgsql_check

Please refer to the above function, run to see if those functions are enabled, if not, you need to adjust the vercel version

**Comment by nguyenanhung** [comment]
@R-N 

Also, after a closer look, I found that your codeigniter directory structure is probably not actually forked from this repository. Please check CodeIgniter version, vercel version (pgsql is enabled from vercel version 0.6.1 and above)

If possible, create a phpinfo endpoint to check, like this one https://codeigniter3-vercel-skeleton.vercel.app/welcome/php to see if your version supports pgsql or not.

Refer to the app/controllers/Welcome.php file

**Comment by R-N** [comment]
> Also, after a closer look, I found that your codeigniter directory structure is probably not actually forked from this repository. Please check CodeIgniter version, vercel version (pgsql is enabled from vercel version 0.6.1 and above)

Yeah I modified your repo to be structured like my CI project. Because I was trying to deploy my existing CI projects to Vercel. I modified yours so that I can pretty much copy replace the files from the Vercel CI repo to my project, save for some files such as database, config, and routes. Not sure why our CI were structured differently, mine is also CI 3. I just noticed these difference of copyright year in index.php when I pasted yours into mine. Maybe my CI 3 base is newer, idk. 

```
- * Copyright (c) 2014 - 2019, British Columbia Institute of Technology
+ * Copyright (c) 2014 - 2018, British Columbia Institute of Technology
```

Anyway, it's available [here](https://github.com/R-N/codeigniter3-vercel-skeleton). 

> I have set up an endpoint to check the function, the result is that the functions are still enabled: https://codeigniter3-vercel-skeleton.vercel.app/welcome/pgsql_check

I see you pushed a commit. I'll try to merge it with my fork.

**Comment by R-N** [comment]
I've enabled the welcome route. I'm getting identical response JSON for [/welcome/pgsql_check](https://raja-laundry-7qnkpj47k-xstinky12gmailcoms-projects.vercel.app/welcome/pgsql_check), so I guess the database works and the issue is indeed on my end. 

I checked [/welcome/php](https://raja-laundry-7qnkpj47k-xstinky12gmailcoms-projects.vercel.app/welcome/php) but I'm not sure what I should be looking for here.

**Comment by R-N** [comment]
Nvm, I see what you meant. Yeah they're supported and enabled.

```
PDO drivers | mysql, pgsql, sqlite

PDO Driver for PostgreSQL | enabled
PostgreSQL(libpq) Version | 14.13

PostgreSQL (libpq) Version | 14.13
Multibyte character support | enabled
Active Persistent Links | 0
Active Links | 1

Directive | Local Value | Master Value
pgsql.allow_persistent | On | On
pgsql.auto_reset_persistent | Off | Off
pgsql.ignore_notice | Off | Off
pgsql.log_notice | Off | Off
pgsql.max_links | Unlimited | Unlimited
pgsql.max_persistent | Unlimited | Unlimited
```

**Comment by R-N** [comment]
So my current issue is not that PostgreSQL isn't enabled. It's that I can't debug. It just dies without error message. 

Should I just close this one and create a new issue?

**Comment by R-N** [comment]
Oh that was dumb. My bad. I forgot the Vercel environment is production so db_debug was false. I can debug now.

**Comment by nguyenanhung** [comment]
@R-N Thanks, I also forgot that in the default database file configuration, I always turn off db_debug :)

**Comment by nguyenanhung** [comment]
@R-N If it's a bug in the core, please give us feedback so we can fix it.

**Comment by R-N** [comment]
I still cant get my project to work but I think it's not due to postgres. I'll close this one. Thank you for your help

**Comment by R-N** [comment]
Oh btw you may want to add quotation marks here to postgre_driver.php in `vendor/nguyenanhung/codeigniter-framework/system`. It fixes warning when schema has dash. 

```
166 - empty($this->schema) OR $this->simple_query('SET search_path TO \''.$this->schema.',public\';');
166 + empty($this->schema) OR $this->simple_query("SET search_path = '{$this->schema},public';");
```

Also got a warning-as-error for `Creation of dynamic property CI_URI::$config is deprecated`. Adding `#[\AllowDynamicProperties]` above `CI_URI` class declaration fixed it. Seems hacky though.

**Comment by R-N** [comment]
Trying to deploy another project and running into this issue again. 
- `could not find driver` for pdo dbdriver with pgsql dsn
- `Call to undefined function pg_connect()` for postgre dbdriver

I've added the following packages to composer but it still doesn't work. Also I searched them at packagist and didn't find them. Maybe adding these don't actually do anything and it was something else that fixed it before.
- ext-pgsql
- ext-pdo_pgsql
- lib-pgsql-libpq

The welcome/pgsql_check page crashes with the database error. I ran phpinfo on index.php and found that there's no "pgsql" anywhere, unlike before. Aside from environment variables, there are only mention of Postgre in Module Authors.

```
PostgreSQL driver for PDO	Edin Kadribasic, Ilia Alshanetsky
PostgreSQL	Jouni Ahto, Zeev Suraski, Yasuo Ohgaki, Chris Kings-Lynne
```

**Comment by R-N** [comment]
[Vercel node version has to be 18](https://github.com/vercel-community/php/issues/572#issuecomment-2430028442)

**Comment by nguyenanhung** [comment]
Hi @R-N , a principle to remember in database design is not to use hyphens (-), plus signs (+) to use in schema, table or column names.

Because this is a special character, in databases it is called a mathematical character (operator) in calculations. So I think it is not advisable to stubbornly create a database with hyphens.

Instead of using hyphens (-), you should use underscores (_) so that SQL parsers do not have problems and do not need to use backticks.

Therefore, I do not think this is a programming error. Because, if you still keep the habit of creating schemas with hyphens (-), then there is a high probability that using them with other languages ​​or frameworks will still encounter errors (not excluding some other frameworks that have polyfilled, but in general, I think you should rename the schema according to the principle).
