### ISSUE TITLE
PHP in HTML script tag cut off

### ISSUE THREAD

**Issue by R-N** [nguyenanhung/codeigniter3-vercel-skeleton#4]
I'm using bs-charts. I'm loading the data by echoing JSON into JS variable in HTML script tag (It's far from ideal, I know). Somehow it breaks into uh I don't how to put it.

Here's my template.

```
    <script src="<?=base_url();?>assets/js/bs-charts.js"></script>
    <script>
      var dataChartPesananHarian = {
        "type": "bar",
        "data": {
          "labels": <?=json_encode(array_map(create_function('$o', 'return $o->HARI;'), $dataPesananHarian));?>,
          "datasets": [
            {
              "label": "Pesanan Bulanan",
              "backgroundColor": "#0041ff",
              "borderColor": "rgba(78, 115, 223, 1)",
              "data": <?=json_encode(array_map(create_function('$o', 'return $o->JUMLAH;'), $dataPesananHarian));?>
            }
          ]
        },
        ...
```

It becomes this. It's really just cut off there. 

```
    <script src="https://raja-laundry.vercel.app/assets/js/bs-charts.js"></script>
    <script>
      var dataChartPesananHarian = {
        "type": "bar",
        "data": {
          "labels": <script async data-explicit-opt-in="true" data-cookie-opt-in="true" src="https://vercel.live/_next-live/feedback/feedback.js"></script>
```

If I open it from incognito window, Vercel's script doesn't get added but it's still cut off at the same point.

```
    <script src="https://raja-laundry.vercel.app/assets/js/bs-charts.js"></script>
    <script>
      var dataChartPesananHarian = {
        "type": "bar",
        "data": {
          "labels": 
```

I don't know if the issue is with Vercel or the CI or my project. It ran fine locally, but the environments are different, so it doesn't mean much.

**Comment by R-N** [comment]
Okay I found it. Yeah there is an error right there, due to PHP version difference (obsolete function removed). However I still find it weird that no errors were shown even in the raw HTML, it's just cut off. Is there a debug flag for this? The previous one was db_debug and this wasn't a db error. 

`A PHP Error was encountered`

**Comment by nguyenanhung** [comment]
Hey @R-N , the problem is in `create_function`, this is a dangerous function, usually in production platforms this function is rarely enabled :)

My advice: You should not use this function in the future, it will potentially contain many security errors.

**Comment by nguyenanhung** [comment]
@R-N I just found it in the official documentation: https://www.php.net/manual/en/function.create-function.php

This function has been DEPRECATED as of PHP 7.2.0, and REMOVED as of PHP 8.0.0. Relying on this function is highly discouraged.

and, Vercel run is PHP 8.3.0

**Comment by nguyenanhung** [comment]
@R-N 
Sorry I didn't read the previous comment.

To turn on error reporting, go to index.php, edit in production case as 

```
error_reporting(-1);
ini_set('display_errors', 1);
```

Or in other words, copy the development section into production

**Comment by R-N** [comment]
> Hey @R-N , the problem is in `create_function`, this is a dangerous function, usually in production platforms this function is rarely enabled :)

Yeah. This one's an old project from my early college years, when I didn't know better. I want to host previews of all my past projects at Vercel (if possible). Still, I appreciate it. Thanks.

> Or in other words, copy the development section into production

Nice. Thanks. I'll close this issue
