### ISSUE TITLE
Cannot find file although it exists

### ISSUE THREAD

**Issue by R-N** [nguyenanhung/codeigniter3-vercel-skeleton#5]
GroceryCRUD fails to run with this error:
```
The template does not exist. Please check your files and try again. 
```
It was raised because the following check returned false:
```
file_exists($this->theme_path.$this->theme.'/views/list_template.php')
```
I echo-ed the path and it was this:
```
assets/grocery_crud/themes/datatables/views/list_template.php
```
But when I checked the source of the deployed build, the path exists. Heck, I can even download [it](https://raja-laundry.vercel.app/assets/grocery_crud/themes/datatables/views/list_template.php). So, why wasn't the file found by file_exists? Is the current working directory not the project root? Edit: Yes it isn't. The cwd is at `/var/task/php`. I suppose I should chdir to `/var/task/user`? Is that safe or will that break stuff?

![image](https://github.com/user-attachments/assets/526ff7e4-b4d4-4a60-bb02-a8606a7e2ee6)

**Comment by R-N** [comment]
I worked around this by prepending `$_SERVER['DOCUMENT_ROOT'] . DIRECTORY_SEPARATOR` to the file path, like you did in index.php. Made a helper around it. Luckily there aren't many to replace. 

Still, I want to know if it's fine to just chdir or if that will break things.

**Comment by nguyenanhung** [comment]
@R-N PHP files should be contained inside the views folder, following the MVC model in its structure, and should not be broken.

In addition, it is true that vercel is a platform, it is not native like normal VPS and hosting, so you should use $_SERVER['DOCUMENT_ROOT'] . DIRECTORY_SEPARATOR to determine the root directory of the project.

**Comment by R-N** [comment]
> @R-N PHP files should be contained inside the views folder, following the MVC model in its structure, and should not be broken.

Agreed. Idk why GroceryCRUD is doing it this way. It's an old version though (1.x), hopefully they've improved it. I don't want to update though, it might break stuff. I just want to get it running (it's done). 

> you should use $_SERVER['DOCUMENT_ROOT'] . DIRECTORY_SEPARATOR to determine the root directory of the project.

So I shouldn't chdir? Alright, got it. Thanks
