### ISSUE TITLE
Slow & Timeout

### ISSUE THREAD

**Issue by R-N** [nguyenanhung/codeigniter3-vercel-skeleton#6]
I noticed that the pages load rather slowly. I thought that was just my connection but apparently that's not it. One of my page ended up in timeout. I have no idea what to do. It's hardly an optimized site but locally it loads in like 1s. At vercel it timed out at 10s. 

It's a monolithic old school project, no API or separation between front/backend, so everything is loaded in one request. This page basically consists of just GroceryCRUD so there's not much I can do (or did). 

Vercel timeout page:
```
This Serverless Function has timed out.

Your connection is working correctly.

Vercel is working correctly.

504: GATEWAY_TIMEOUT
Code: FUNCTION_INVOCATION_TIMEOUT
ID: sin1:sin1::slnss-1731669563270-95b1afa41c96
```

Log:
```
🐘 Spawning: PHP Built-In Server at /var/task/user (document root) and /var/task/user/api/index.php (router)
🐘STDERR: [Fri Nov 15 11:13:26 2024] PHP 8.3.8 Development Server (http://127.0.0.1:8000) started

🐘 Accessing raja-laundry.vercel.app/pesanan?%2Fpesanan=
🐘 Querying /pesanan?%2Fpesanan=
🐘STDERR: [Fri Nov 15 11:13:26 2024] 127.0.0.1:47038 Accepted
[Fri Nov 15 11:13:26 2024] 127.0.0.1:47038 Closed without sending a request; it was probably just an unused speculative preconnection
[Fri Nov 15 11:13:26 2024] 127.0.0.1:47038 Closing
[Fri Nov 15 11:13:26 2024] 127.0.0.1:47040 Accepted
```
```
🐘 Accessing raja-laundry.vercel.app/pesanan?%2Fpesanan=
🐘 Querying /pesanan?%2Fpesanan=
🐘STDERR: [Fri Nov 15 10:58:45 2024] 127.0.0.1:39144 Accepted
```

**Comment by nguyenanhung** [comment]
@R-N I'm not sure what your problem is, however, in my opinion, Vercel is suitable for microservice models, no interface.

In fact, my applications have not been slow.

To debug, I think you should adjust the config.php file, adjust the logs directory to be on the same level as index.php

Configure vercel.json to be able to view the logs file on the browser, from there will be clearer information.

**Comment by R-N** [comment]
> To debug, I think you should adjust the config.php file, adjust the logs directory to be on the same level as index.php

Ok

> Configure vercel.json to be able to view the logs file on the browser, from there will be clearer information.

How do I do that? Vercel runtime logs seem to only consist of request logs.

**Comment by R-N** [comment]
Would the log have anything useful? 
Maybe I should set up a profiler

**Comment by nguyenanhung** [comment]
@R-N Open Source is where you can do whatever you want to solve your problems :D

**Comment by R-N** [comment]
My bad. Profiling shows that the database queries are slow. It's actually due to compress_htmlercel misconfiguration that the postgre database and the app are from different regions. Closing.
